name: football_time_booker
packages:
  - modules/*
  - modules/common_base/modules/*

command:
  bootstrap:
    # runPubGetInParallel: true
    usePubspecOverrides: true
    post:
      - melos run format
    dependencies:
      analyzer: 7.7.1
      get_it: 8.2.0
      bloc: 9.1.0
      flutter_bloc: 9.1.1
      equatable: 2.0.7
      auto_route: 10.1.2 

    dev_dependencies:
      flutter_gen_runner: 5.12.0
      build_runner: 2.5.4
      auto_route_generator: 10.1.0
      
      

scripts:
  gen:
    run: fvm flutter pub run build_runner build --delete-conflicting-outputs
    exec:
      concurrency: 5
      failFast: true
    description: Run the command in the selected module.
    select-package:
      flutter: true
      dir-exists: lib
    packageFilters:
      dependsOn: build_runner
      noDependsOn: envied
      ignore: localization