name: football_time_booker
packages:
  - modules/*
  - modules/common_base/modules/*

command:
  bootstrap:
    # runPubGetInParallel: true
    usePubspecOverrides: true
    post:
      - melos run format
    dependencies:
      dropdown_button2: 2.3.9
      talker: 5.0.2
      firebase_auth: 6.1.1
      firebase_core: 4.2.0 
      cloud_firestore: 6.0.3
      mask_text_input_formatter: 2.9.0
      objectbox_flutter_libs: 4.3.0
      objectbox: 4.3.0
      freezed_annotation: 3.1.0
      analyzer: 7.7.1
      get_it: 8.2.0
      bloc: 9.1.0
      flutter_bloc: 9.1.1
      equatable: 2.0.7
      auto_route: 10.1.2 

    dev_dependencies:
      objectbox_generator: 4.3.0
      freezed: 3.1.0
      json_serializable: 6.9.5
      flutter_gen_runner: 5.12.0
      build_runner: 2.5.4
      auto_route_generator: 10.1.0
      
      

scripts:
  gen:
    run: fvm flutter pub run build_runner build --delete-conflicting-outputs
    exec:
      concurrency: 5
      failFast: true
    description: Run the command in the selected module.
    select-package:
      flutter: true
      dir-exists: lib
    packageFilters:
      dependsOn: build_runner
      noDependsOn: envied
      ignore: localization