name: navigation
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

sdkPath: .fvm/versions/3.29.3

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  get_it: 8.2.0
  auto_route: 10.1.2
  flutter:
    sdk: flutter
  
  auth: 
    path: ../../../auth 
  common_base: 
    path: ../../../common_base

dev_dependencies:
  build_runner: 2.5.4
  auto_route_generator: 10.1.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

